/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package account_statement_analysis;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.jfr.consumer.EventStream;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import sql.DBConnection;

/**
 *
 * @author pablo
 */
public class InitialPageForm extends javax.swing.JFrame {

    /**
     * Creates new form InitialPageForm
     */
    
    private final JFileChooser openFileChooser;
    private String downloadsPath;
            
    public InitialPageForm() {
        initComponents();
        
        downloadsPath = System.getProperty("user.home") + "/Downloads/";
        openFileChooser = new JFileChooser(new File(downloadsPath));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("XLS files", "xls"));
        
        ReadAccountStaements();
    
    }
    
    private boolean IsItNumber(String string){
        try {
            int intValue = Integer.parseInt(string);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void ReadAccountStaements(){
        try {
            var path = "C:\\Users\\pablo\\Downloads\\Estado de cuenta dol.xls";
            FileInputStream file = new FileInputStream(new File(path));
            HSSFWorkbook wb = new HSSFWorkbook(file);
            HSSFSheet sheet = wb.getSheetAt(0);
            //"C:\Users\pablo\AppData\Local\Temp\"
            PrintWriter writer = new PrintWriter(System.getProperty("java.io.tmpdir") + "test.txt", "UTF-8");
            
            DBConnection conn = new DBConnection();
            conn.StartConnection();
            
            var stop = false;
            
            for (Row row : sheet){
                if (row.getRowNum() >= 7){
                    for (Cell cell : row){
                        if (cell.getColumnIndex() == 0 && !IsItNumber(cell.toString())){
                            stop = true;
                            break;
                        }
                        if (cell.getColumnIndex() == 1 || cell.getColumnIndex() == 2){
                            if (cell != null){
                               writer.print(cell.toString() + " "); 
                            }
                        }else if (cell.getColumnIndex() == 4 || cell.getColumnIndex() == 5 ){
                            if (cell.getColumnIndex() == 5){
                                var rownow = row.getRowNum();
                                var value = wb.getSheetAt(0).getRow(rownow).getCell(4); 
                                if (value == null && cell != null){
                                    writer.print(cell.toString() + " "); 
                                }
                            }else{
                                if (cell != null){
                                    writer.print(cell.toString() + " "); 
                                }
                            }
                        }
                    }
                    writer.println("");
                    if (stop){
                        writer.close(); 
                        break;
                    }
            
                }
            }
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Uplode");

        jMenuItem1.setText("Estado de Cuenta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        int returnValue = openFileChooser.showOpenDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            String filePath = openFileChooser.getSelectedFile().toString();
            //ReadAccountStaements(filePath);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialPageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
